### PR TITLE
Fixes #320

### LINKED ISSUE #320: Coordinate Conversion: Input becomes unresponsive after Ambiguous Coordinate dialog ignored. (ArcMap)
Version
ArcGIS Desktop10.5.

Tested against Build: 1413

Steps to reproduce:
1.  Open ArcMap and Coordinate Conversion Addin
2. Add DD, DDM, DMS are new output coordinates.
3. In the Input box, enter: 45.0+ 100.0-
4.  You should get a the Ambiguous Coordinates dialog box pop up.
5.  Close the window without hitting the "OK" button.
6. Enter another ambiguous coordinate such as: 45.0+ 100.0+
7. Note it no longer gives you a coordinate.
8. Close ArcMap and enter the same ambiguous coordinate as above.  It now works.

### PR DESCRIPTION
**Pull request by kgonzago**
Got rid of close button from ambiguous dialog.

@csmoore Please review and merge when you get a chance.

### CODE REVIEW

File: source/CoordinateConversion/CoordinateConversionLibrary/Behaviors/WindowBehavior.cs [hunk 1]
```diff
@@ -0,0 +1,133 @@
+﻿using System;
```
Comment (csmoore) [inline source/CoordinateConversion/CoordinateConversionLibrary/Behaviors/WindowBehavior.cs]: Minor: license header

Comment (csmoore) [inline source/CoordinateConversion/CoordinateConversionLibrary/Behaviors/WindowBehavior.cs]: Maybe also a short comment to explain why this solution is necessary - i.e. WPF doesn't expose this window style
